default: &DEFAULT
  Host: <host>
  Port: 3306
  User: binlog
  Password: <password>
  IncludeTables:
    - binlogtest.event
  Flavor: mysql
dev:
  <<: *DEFAULT
  Env: dev
stage:
  <<: *DEFAULT
  Env: stage
prod:
  <<: *DEFAULT
  Env: prod


